feature: Russian translation
amp-letter/amp-letter.github.io pull request #380
Opened 2018-01-10 16:45 UTC by FoxWhite

I've added a Russian translation. Please review :)

2018-01-10 16:57 UTC, HerrBertling commented
You need to adjust the CSS as well – I did a german translation in #30, just check the files in there. The change is pretty straightforward :) https://github.com/amp-letter/amp-letter.github.io/pull/30/files

2018-01-10 17:02 UTC, FoxWhite commented
@HerrBertling cheers, fixed it

2018-01-10 22:16 UTC, triblondon commented
Could a native Russian speaker please review?

2018-01-11 06:55 UTC, sameoldmadness requested changes

2018-01-11 06:55 UTC, sameoldmadness commented on index.html
> +				<p>Мы сообщество людей, в высшей степени заинтересованных в развитии и благосостоянии Всемирной паутины ("веба"), и мы <strong>глубоко обеспокоены</strong> проектом <a href='https://ampproject.or
Probably, "Мы – сообщество людей".

2018-01-11 06:55 UTC, sameoldmadness commented on index.html
> +				<p>Мы сообщество людей, в высшей степени заинтересованных в развитии и благосостоянии Всемирной паутины ("веба"), и мы <strong>глубоко обеспокоены</strong> проектом <a href='https://ampproject.or
> Всемирной паутины ("веба")

"Сети" or leave "The Web" as is.

2018-01-11 06:55 UTC, sameoldmadness commented on index.html
> +								<p>Фактически AMP удерживает пользователей в домене Google, тем самым уводя трафик с других сайтов в пользу последнего. В масштабе миллионов пользователей это <strong>усиливает и без того рас
> доминирование Google над вебом

"Доминирование _в_ Сети", not "над".

2018-01-11 06:55 UTC, sameoldmadness commented on index.html
> +								<p>Мы признаем проблему медленной загрузки веб-страниц относительно альтернативных проприетарных технологий, таких как <a href='https://instantarticles.fb.com/'>Facebook Instant Articles</a>
> UX

User experience better be translated the same way everywhere. "Пользовательский опыт" would do fine.

2018-01-11 06:55 UTC, sameoldmadness commented on index.html
> +								<p>Поисковые системы обладают достаточным влиянием, чтобы решить эту проблему. Однако, Google решили предоставить преимущественную позицию в верхней части выдачи (для статей) и иконку с "молн
> преимущественную

привилегированную

2018-01-11 06:55 UTC, sameoldmadness commented on index.html
> +								<p>Поисковые системы обладают достаточным влиянием, чтобы решить эту проблему. Однако, Google решили предоставить преимущественную позицию в верхней части выдачи (для статей) и иконку с "молн
> иконку с "молнией"

quotes may be omitted

2018-01-11 06:55 UTC, sameoldmadness commented on index.html
> +								<p>Поисковые системы обладают достаточным влиянием, чтобы решить эту проблему. Однако, Google решили предоставить преимущественную позицию в верхней части выдачи (для статей) и иконку с "молн
> для тех сайтов, которые используют технологию

for the sake of simplicity one could use "для сайтов, использующих технологию"

2018-01-11 06:55 UTC, sameoldmadness commented on index.html
> +									<li>Контент, который "вибирает" путь AMP и соответствующий хостинг на домене Google, поощряется преимущественным поисковым продвижением, включая (в случае новостных статей) позицию выше оста
> "вибирает"

typo, should be "выбирает"

2018-01-11 06:55 UTC, sameoldmadness commented on index.html
> +									<li>Контент, который "вибирает" путь AMP и соответствующий хостинг на домене Google, поощряется преимущественным поисковым продвижением, включая (в случае новостных статей) позицию выше оста
> поощряется преимущественным поисковым продвижением

maybe, "получает преимущество в поисковом продвижении"?

2018-01-11 06:55 UTC, sameoldmadness commented on index.html
> +								<p>Если целью Google AMP действительно является улучшение пользовательского опыта в Интернете, мы предлагаем несколько простых изменений, которые послужат этой цели, и в то же время позволят
> вебу

"Сети" or "Интернету"

2018-01-11 06:55 UTC, sameoldmadness commented on index.html
> +									<li>Не показывать внешний контент внутри экосистемы Google, кроме тех случаев, когда пользователям очевидно, что в данный момент они используют продукт Google. Запустить новостной аггрегатор
> аггрегатор

агрегатор

> содержащию

содержащую 

> на URL Google

probably, "в домене Google"

2018-01-11 06:55 UTC, sameoldmadness commented on index.html
> +								<p>Тем не менее, разработчики не должны быть вынуждены держать свой контент под крылом Google из-за доминирования последнего на поисковом рынке.<strong>Веб это не Гугл, и не должен быть тольк
> Веб это не Гугл

Веб – это не Гугл

2018-01-11 06:55 UTC, sameoldmadness commented on index.html
> +				<p class='note'>For signatories please refer to the <a href='?lang=en' data-langswitch='en'>English version</a>.  Translations are provided for information but should not be considered normative.
Shouldn't this section be translated?

2018-01-11 06:55 UTC, sameoldmadness commented on index.html
> +								<p>Тем не менее, разработчики не должны быть вынуждены держать свой контент под крылом Google из-за доминирования последнего на поисковом рынке.<strong>Веб это не Гугл, и не должен быть тольк
Google should be either translated in all occurrences or not. 

Personally, I prefer leaving it untranslated.

2018-01-11 08:59 UTC, bel0v commented on index.html
> +								<p>Мы признаем проблему медленной загрузки веб-страниц относительно альтернативных проприетарных технологий, таких как <a href='https://instantarticles.fb.com/'>Facebook Instant Articles</a>
UX, как мне кажется, это вполне устоявшийся термин. "Пользовательский опыт" немного режет слух.

2018-01-11 09:01 UTC, FoxWhite commented on index.html
> +								<p>Поисковые системы обладают достаточным влиянием, чтобы решить эту проблему. Однако, Google решили предоставить преимущественную позицию в верхней части выдачи (для статей) и иконку с "молн
for the sake of simplicity я как раз не использовал причастие, потому что далее идет целый ряд причастий, относящихся к другому. Пусть чуть сложнее, но воспринимается легче

2018-01-11 09:03 UTC, FoxWhite commented on index.html
> +								<p>Если целью Google AMP действительно является улучшение пользовательского опыта в Интернете, мы предлагаем несколько простых изменений, которые послужат этой цели, и в то же время позволят
agreed

2018-01-11 09:04 UTC, FoxWhite commented on index.html
> +									<li>Не показывать внешний контент внутри экосистемы Google, кроме тех случаев, когда пользователям очевидно, что в данный момент они используют продукт Google. Запустить новостной аггрегатор
agreed

2018-01-11 09:04 UTC, FoxWhite commented on index.html
> +								<p>Тем не менее, разработчики не должны быть вынуждены держать свой контент под крылом Google из-за доминирования последнего на поисковом рынке.<strong>Веб это не Гугл, и не должен быть тольк
agreed

2018-01-11 09:07 UTC, FoxWhite commented on index.html
> +								<p>Поисковые системы обладают достаточным влиянием, чтобы решить эту проблему. Однако, Google решили предоставить преимущественную позицию в верхней части выдачи (для статей) и иконку с "молн
not sure what's better :)

2018-01-11 09:07 UTC, FoxWhite commented on index.html
> +								<p>Фактически AMP удерживает пользователей в домене Google, тем самым уводя трафик с других сайтов в пользу последнего. В масштабе миллионов пользователей это <strong>усиливает и без того рас
agreed

2018-01-11 09:07 UTC, FoxWhite commented on index.html
> +				<p>Мы сообщество людей, в высшей степени заинтересованных в развитии и благосостоянии Всемирной паутины ("веба"), и мы <strong>глубоко обеспокоены</strong> проектом <a href='https://ampproject.or
agreed

2018-01-11 09:08 UTC, FoxWhite commented on index.html
> +				<p class='note'>For signatories please refer to the <a href='?lang=en' data-langswitch='en'>English version</a>.  Translations are provided for information but should not be considered normative.
fixed

2018-01-11 11:07 UTC, sameoldmadness commented on index.html
> +								<p>Мы признаем проблему медленной загрузки веб-страниц относительно альтернативных проприетарных технологий, таких как <a href='https://instantarticles.fb.com/'>Facebook Instant Articles</a>
Тогда стоит поправить оставшиеся два вхождения "пользовательского опыта" на UX.

2018-01-11 11:08 UTC, sameoldmadness commented on index.html
> +								<p>Поисковые системы обладают достаточным влиянием, чтобы решить эту проблему. Однако, Google решили предоставить преимущественную позицию в верхней части выдачи (для статей) и иконку с "молн
ок

2018-01-11 11:08 UTC, sameoldmadness commented on index.html
> +								<p>Поисковые системы обладают достаточным влиянием, чтобы решить эту проблему. Однако, Google решили предоставить преимущественную позицию в верхней части выдачи (для статей) и иконку с "молн
ок

2018-01-11 11:10 UTC, sameoldmadness approved these changes

2018-01-11 16:57 UTC, triblondon commented
Please use the same indentation style as the rest of the document.  Then if multiple Russian speakers are happy with this I'll merge it.

2018-01-13 18:22 UTC, triblondon commented
On the basis of the earlier approval I'll go ahead and merge this.

2018-01-13 18:24 UTC, merged