Chinese Traditional
amp-letter/amp-letter.github.io pull request #684
Opened 2018-01-28 14:44 UTC by NoobTW

A translation of Chinese Traditional.

2018-02-02 13:43 UTC, triblondon commented
Thanks!  One CSS change missing, and we need a review from a second native speaker

2018-02-02 15:02 UTC, NoobTW commented
Fix that CSS change. Looking for second native speaker.

2018-02-03 05:51 UTC, aver803bath5 commented
I think "If Google’s objective with AMP is indeed to improve user experience on the Web" translated to 「如果 Google 的目標確定是透過 AMP 來改善網路上的使用者體驗的話」。

2018-02-03 06:27 UTC, aver803bath5 commented
"Instead of granting premium placement in search results only to AMP, provide the same perks to all pages that meet an objective, neutral performance criterion such as Speed Index. Publishers can then use any technical solution of their choice." could be translated into 「不再只提供優先的搜尋結果位置給使用 AMP 技術的頁面，而是利用其他符合客觀且中立的標準如 Speed Index 來排定所有頁面的搜尋結果的順序，這樣一來出版者就可以使用任何他們想要的技術解決方案。」

2018-02-03 07:24 UTC, aver803bath5 commented
"Do not display third-party content within a Google page unless it is clear to the user that they are looking at a Google product. It is perfectly acceptable for Google to launch a “news reader”, but it is not acceptable to display a page that carries only third party branding on what is actually a Google URL, nor to require that third party to use Google’s hosting in order to appear in search results." this paragraph should to translated into 「除非使用者清楚知道他們正在查看一個 Google 的產品，否則不要在 Google 的頁面展示第三方的內容，Google 推出一個『新聞閱讀器』是完全可以被接受的事情，但是展示一個只帶有第三方的品牌實際上卻是一個 Google 連結的頁面或是要求第三方團體使用 Google 託管的服務以換取較優勢的搜尋結果都是不能夠被接受的事情。」

2018-02-03 07:40 UTC, aver803bath5 commented
"AMP can remain one of a range of technologies that give publishers high quality options for delivering Web pages quickly and making users happy." this sentence could to translated into 「AMP 可以保持為其中一種技術，為出版商提供快速交付網頁以及讓使用者高興的高品質選項。」

2018-02-03 08:14 UTC, NoobTW commented
Thank you @aver803bath5. You should review on the code instead of commenting here (?

2018-02-03 08:36 UTC, aver803bath5 requested changes
Some translation suggestions.

2018-02-03 08:36 UTC, aver803bath5 commented on index.html
> +				<p>如果 Google 透過 AMP 的目標確實是為了改善使用者在網路上的體驗，那我們建議做一些簡單的改變，當然同時保留 Web 的動態性、競爭性和消費者導向：</p>
「如果 Google 的目標確定是透過 AMP 來改善網路上的使用者體驗的話」第一句這樣翻也許比較順暢一點。

2018-02-03 08:36 UTC, aver803bath5 commented on index.html
> +					<li>不再將搜尋結果的優良位置留給 AMP，並公平留給使用其他客觀的、中性的性能標準如 <a href="https://sites.google.com/a/webpagetest.org/docs/using-webpagetest/metrics/speed-index">Speed Index</a>。出版者可以選擇任何他們想要的技術方案。</li>
「不再只提供優先的搜尋結果位置給使用 AMP 技術的頁面，而是利用其他符合客觀且中立的標準如 Speed Index 來排定所有頁面的搜尋結果的順序，這樣一來出版者就可以使用任何他們想要的技術解決方案。」我想這樣比較貼近原意

2018-02-03 08:36 UTC, aver803bath5 commented on index.html
> +					<li>除非使用者正在查看 Google 產品，否則不要在 Google 頁面中顯示第三方內容。若 Google 推出「新聞閱讀器」是完全可以被接受的；但是在實際上是 Google 的網址中顯示一個只包含第三方品牌的網頁，或是要求使用 Google 的推廣服務來顯示在搜尋結果上很難被接受。</li>
「除非使用者清楚知道他們正在查看一個 Google 的產品，否則不要在 Google 的頁面展示第三方的內容，Google 推出一個『新聞閱讀器』是完全可以被接受的事情，但是展示一個只帶有第三方的品牌實際上卻是一個 Google 連結的頁面或是要求第三方團體使用 Google 託管的服務以換取較優勢的搜尋結果都是不能夠被接受的事情。」我想這樣翻譯會比較清楚且較通順。

2018-02-03 08:36 UTC, aver803bath5 commented on index.html
> +				<p>我們並不想阻止 Google 在 AMP 上的開發，這些更改並不需要這樣做，我們也讚許搜尋引擎依照網頁速度來排序搜尋結果。AMP 可以保持為一種讓出版者提供網頁並讓使用者開心的高品質技術。</p>
「AMP 可以保持為其中一種技術，為出版商提供快速交付網頁以及讓使用者高興的高品質選項。」第二句這樣翻譯應該比較理想，比較貼近中文文法。

2018-02-03 08:51 UTC, NoobTW commented on index.html
> +					<li>除非使用者正在查看 Google 產品，否則不要在 Google 頁面中顯示第三方內容。若 Google 推出「新聞閱讀器」是完全可以被接受的；但是在實際上是 Google 的網址中顯示一個只包含第三方品牌的網頁，或是要求使用 Google 的推廣服務來顯示在搜尋結果上很難被接受。</li>
我覺得這個跟原意不太一樣 (?

2018-02-14 01:52 UTC, triblondon commented
Can we get another review from @aver803bath5?

2018-02-15 05:05 UTC, aver803bath5 approved these changes
I think the translation has no big problem. This translation is ready to go. Thank you @triblondon . Sorry for late reply. And thank you @NoobTW for doing such great translation.

2018-02-15 05:05 UTC, aver803bath5 commented on index.html
> +					<li>除非使用者正在查看 Google 產品，否則不要在 Google 頁面中顯示第三方內容。若 Google 推出「新聞閱讀器」是完全可以被接受的；但是在實際上是 Google 的網址中顯示一個只包含第三方品牌的網頁，或是要求使用 Google 的推廣服務來顯示在搜尋結果上很難被接受。</li>
「但是在實際上是 Google 的網址中顯示一個只包含第三方品牌的網頁，或是要求使用 Google 的推廣服務來顯示在搜尋結果上很難被接受。」主要是這一句話因為文法上的關係感覺上不好懂，有點太生硬的感覺。

2018-02-15 05:05 UTC, aver803bath5 commented on index.html
> +					<li>不再將搜尋結果的優良位置留給 AMP，並公平留給使用其他客觀的、中性的性能標準如 <a href="https://sites.google.com/a/webpagetest.org/docs/using-webpagetest/metrics/speed-index">Speed Index</a>。出版者可以選擇任何他們想要的技術方案。</li>
「出版者可以選擇任何他們想要的技術方案。」前面加上個「這樣一來」會不會比較通順？

2018-02-21 11:34 UTC, merged

2018-02-21 11:35 UTC, triblondon commented
Thanks all.